### PR TITLE
Replace google play badge

### PR DESCRIPTION
**Pull request by EsteveAguilera**
This PR fixes the issue #10 

I've used the URL https://play.google.com/intl/en_us/badges/ but it does not give option to download SVG files, so I've got to use the PNG one

### CODE REVIEW

**Review by rocboronat — COMMENTED** [review]
Hummm not sure about replacing a shiny svg with a poor png. How it appears in a phone? The svg was pixel perfect.

**Comment by EsteveAguilera** [comment]
I agree that svg is always better than png...
I've just seen that the web can generate eps files, but I do not have Adobe Ilustrator to convert from eps to svg :S

**Comment by rocboronat** [comment]
I found this on Google: http://www.zamzar.com/convert/eps-to-svg/

(never tried it 😅)

**Comment by EsteveAguilera** [comment]
Hmmm.... I don't like this kind of tools.
Will try to find a better way to convert from EPS to SVG.
The issue was opened 6 months ago, so there's no need to hurry 😅

**Comment by EsteveAguilera** [comment]
Ok, I see that with Affinity Designer I can open the EPS and export to SVG for the web.

If we keep the SVG format, this issue can be fixed with a single commit, so I will close this PR and open a new one that only replaces the old SVG with the new ones. Let's keep the git history clean!

**Comment by rocboronat** [comment]
Nice!

**Pull request closed without merging**
